remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: assets/img/logo1.png
#description: text below image
show_downloads: true
title: Minh K. Chau
description: I like data. My strengths are research methodology, data science, and healthcare. It is my goal to write an algorithm that can enhance accuracy in diagnosing psychological and psychiatric disorders. I enjoy learning from others, lets connect! </br> PS: *My cat is pretty (I have her picture at the end of this page). And I am pleasant to work with, I promise!*  
