remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: assets/img/logo1.png
#description: text below image
title: MINH K. CHAU
description: Research rocks, data science rules, stats are fun, but banh mi is the best. I am easy to work with, I promise!
